### PR TITLE
Feature/translations

### PR DESCRIPTION
**Pull request by Amitom**
@jpuri And voilà ! :)

### CODE REVIEW

**Comment by Amitom** [comment]
Sorry but the rebase create a lot of issues, I'm currently trying to resolve this issues.

**Comment by jpuri** [comment]
Hey @Amitom: editor is starting now in dev mode but test cases are still broken :(
Can you plz check - I want to release this soon.

**Comment by Amitom** [comment]
Is it my fault ? Because, per example, there is 4 fails on ColorPicker control but I didn't make any change on it.

If you want I will take a look this evening. :/

**Comment by Amitom** [comment]
I'll see this evening. I can't before.

**Comment by jpuri** [comment]
Ok, try to do it earliest. A couple of other PRs are stuck coz of this.

**Comment by roychoo** [comment]
@jpuri, to prevent other PRs from blocking, do we want to first revert this PR?

**Comment by jpuri** [comment]
Hey @roychoo, I will fix and resolve it over the weekend.

**Pull request merged**
