### PR TITLE
do not add trailing space & do not lose focus when inserting links

### PR DESCRIPTION
**Pull request by joejoejoew**

### CODE REVIEW

**Comment by jpuri** [comment]
HI, the focus change looks good. But removing the space has issue as if I do not do that the test written right after the link will also be part of link.

Plz suggest.

**Comment by erikmueller** [comment]
I haven't looked into draftsjs workings but what about just checking if there already IS a space coming after the elected block?

could https://github.com/jaminmelville/react-draft-wysiwyg/commit/24d334ad6d0aa46afd616c48a175172e98ab2022 help?

**Comment by anlesk** [comment]
Any updates on that? Focus loss is still an issue.

**Comment by abannach** [comment]
> Any updates on that? Focus loss is still an issue.

Second this, We've run into both of these problems and it's causing an unideal user experience.

**Comment by preetriti1** [comment]
Is there any plan to get the focus change in first? This issue is still present and not a good experience.

**Pull request closed without merging**
