### PR TITLE
Feature for the user decides where the link should open

### PR DESCRIPTION
**Pull request by acidio**
I added the option "New window" or "Main window", I set the main window as default on the toolbar config.

If need more improvements please tell me, I really like the project.

Thanks

### CODE REVIEW

**Comment by jpuri** [comment]
Hey @acidio: Looks good.

Thanks for the wonderful work. Can you also plz resolve conflicts with the latest code and some files have changes in just newline character - can you plz fix that.

**Comment by alfaslash** [comment]
@acidio Could you add these string without translate
```
'components.controls.link.linkTargetOption': 'Target',
'components.controls.link.linkTargetOption.MainWindow': 'Main window',
'components.controls.link.linkTargetOption.NewWindow': 'New window',
```
in another locale files: (i18n/ru.js, /18n/fr.js, i18n/zh.js)?

**Comment by acidio** [comment]
Hi @jpuri, I solved the conflicts for this pull request.
I need to add the translations yet.
And to remember, we need to check this PR here https://github.com/jpuri/html-to-draftjs/pull/15 to get the target option working from draft to HTML to draft again.

Thanks

**Comment by acidio** [comment]
Now I think we have everything :)

**Comment by gregBerthelot** [comment]
@acidio default target should be different if the link is internal or external

Internal link (same domain) => _self
External link => _blank

**Comment by alfaslash** [comment]
@gregBerthelot, no such condition in the [specification](https://www.w3.org/TR/html5/text-level-semantics.html#the-a-element).
You can specify `target` on any of their conditions.

**Comment by jpuri** [comment]
Thanks @acidio ,

Sorry for delay I was away on short vacation last 2 days. I will merge and release it this weekend.

**Comment by jpuri** [comment]
Thanks a lot @acidio

**Comment by jpuri** [comment]
Just release `react-draft-wysiwyg@1.9.4` with the change. Also, I did small change in link option popup.
screen shot 2017-04-16 at 1 51 11 pm

**Pull request merged**
