### PR TITLE
Fixes/firefox safari image error

### PR DESCRIPTION
**Pull request by gablabelle**
This is a fix for issue #238 

Thanks to @lavoiedn for his help on this.

Tested on:
Firefox Dev Edition 54.0a2 (2017-03-16) (64-bit)
Chrome 56.0.2924.87 (64-bit)
Safari 10.0.3 (12602.4.8)

### CODE REVIEW

**Comment by lavoiedn** [comment]
Note that this implementation prevents the user from deleting images.

Needs more work.

**Comment by gablabelle** [comment]
@lavoiedn Now fixed with 21a73cc77104e931deaee919e5933eb00a9a5aea

**Comment by jpuri** [comment]
Hey @gablabelle: thanks a lot for the PR, I will soon check it 👍

**Comment by jpuri** [comment]
Hey @gablabelle: 

Apologies for being so late.

I checked the PR today, its not very clear. Looks to me actual fix is `.indexOf(label) !== -1` instead of `includes`. Can you please let me know.

**Comment by gablabelle** [comment]
@jpuri .indexOf(label) !== -1 instead of .includes will prevent crash in Internet Explorer since .includes is not support in IE. 


https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/includes#Browser_compatibility

But please please note the main focus of this branch `fixes/firefox-safari-image-error` is that it contains the fixes for safari and firefox issue #238

**Comment by pgambling** [comment]
Any chance this PR will be merged soon? I'm dealing with this same issue described in #238.

**Comment by jpuri** [comment]
Thanks a lot @gablabelle , inspired by changes in this PR. I fixed the issue. https://github.com/jpuri/react-draft-wysiwyg/issues/238

Closing this one.

**Pull request closed without merging**
