### PR TITLE
added the ability to provide a custom component to hashtag and mention

### PR DESCRIPTION
**Pull request by davidpett**
in order to use things like react-router `<Link/>` component, or to simply change the URL of the mention or hashtag

### CODE REVIEW

**Comment by jpuri** [comment]
Hey @davidpett , good work and sorry for delayed reply. Can you plz change the target branch to `develop` I want to just play around with the storybook before releasing the feature.

Thanks a lot for this contribution.

**Comment by jpuri** [comment]
Thanks a lot 👍

**Comment by jpuri** [comment]
Hey @davidpett : great work, I added this small change: https://github.com/jpuri/react-draft-wysiwyg/commit/14cb88e2cc1a0773d1d71a3d0e07a249583d5e68

I will release this soon.

**Comment by nabeel-v** [comment]
@jpuri Colud you release these changes it would be great feature

**Pull request merged**
