### PR TITLE
Add customizable labels for blockTypes

### PR DESCRIPTION
**Pull request by Amitom**
Hi Jyoti,

I will try, step by step, to add "translations" capabilities in the components. First : blockType displayNames :)

### CODE REVIEW

**Comment by space11** [comment]
@Amitom Hi, Im struggling when try to use custom labels for blockTypes. Is there any manual on that feature ?
Thanks.

**Comment by space11** [comment]
I tried to use `displayNames` property but with no joy.
```JS
const documentEditorToolBarOptions = {
  options: [
    'inline',
    'blockType',
    'list',
    'colorPicker',
    'link',
    'image',
  ],
  blockType: {
    inDropdown: true,
    options: [
      'Normal',
      'H1',
      'H2',
      'H3',
      'H4',
      'H5',
      'H6',
      'Blockquote',
    ],
    displayNames: [
      { label: 'Normal', displayName: 'Normal', style: 'unstyled' },
      { label: 'H1', displayName: 'Heading 1', style: 'header-one' },
      { label: 'H2', displayName: 'Heading 2', style: 'header-two' },
      { label: 'H3', displayName: 'Heading 3', style: 'header-three' },
      { label: 'H4', displayName: 'Heading 4', style: 'header-four' },
      { label: 'H5', displayName: 'Heading 5', style: 'header-five' },
      { label: 'H6', displayName: 'Heading 6', style: 'header-six' },
      { label: 'Blockquote', displayName: 'Blockquote', style: 'blockquote' },
    ],
    className: undefined,
    component: undefined,
    dropdownClassName: undefined,
  },
};

**Comment by Amitom** [comment]
Hi @space11 , this feature disappeared with [translations](https://github.com/jpuri/react-draft-wysiwyg/blob/master/src/i18n/en.js) support, search for "translation" in [this page](https://jpuri.github.io/react-draft-wysiwyg/#/docs) to know how to change locale.

**Comment by space11** [comment]
@Amitom Thanks man.

**Pull request closed without merging**
