### PR TITLE
Feature: Custom linkifier on Link component

### PR DESCRIPTION
**Pull request by seromenho**
We don't want to use linkify-it.
In the first place I was thinking just to use a custom function to validate the link but we also need to change the `targetOption` in some scenarios. 

This PR comes with a `beforeAddLink` function that receives all params from onChange and should return them all again (changed or not).

Eg: For those who don't want at all linkify-it your link configuration could be as follow

```js
link: {
...
beforeAddLink: (params) => params 
}
```

What do you guys think?
Open to suggestion, maybe the namings could be improved and some other things.

Thanks

### CODE REVIEW

**Comment by seromenho** [comment]
Maybe this could also resolve #674 #650 and #601

**Comment by jpuri** [comment]
Hey @seromenho : I would prefer a callback like this: https://github.com/jpuri/react-draft-wysiwyg/blob/master/src/config/defaultToolbar.js#L329

I mean making the callback a part of toolbar config. Can you plz update the PR for this. Or do you have a specific reason for preferring above approach.

**Comment by seromenho** [comment]
@jpuri Sure, I had no reason other than saw the imageUploadCallback also there. 
PR updated. Do you think we should also move the default linkifier to the defaultToolbar.js or it's fine as it is?

**Comment by jpuri** [comment]
@seromenho : yep I would suggest moving it. `imageUploadCallback` is actually at both places in config and also as props.
Reason is that it existed even before I added toolbar config, so I left it in props for backward compatibility.

**Comment by seromenho** [comment]
@jpuri Thanks. Pushed the update.

**Comment by jpuri** [comment]
Hey @seromenho : sorry for delay, I will review and merge this soon.

**Comment by seromenho** [comment]
@jpuri sure. No worries. Let me know if I can help resolving the conflicts. I've seen you merged #775 
Thanks

**Comment by jpuri** [comment]
Thanks a lot @seromenho 👍

**Comment by jpuri** [comment]
Hey @seromenho , its released `react-draft-wysiwyg@1.13.1`. I renamed it to `linkCallback`.

**Pull request merged**
