### PR TITLE
added support for suggestion callback

### PR DESCRIPTION
**Pull request by nitinagrawal08**

### CODE REVIEW

**Comment by jpuri** [comment]
Hi @nitinagrawal08 ,

This change will execute callback on each rendering of suggestion. It should be each typing of user.
I can not merge at as it is atm.

**Comment by nitinagrawal08** [comment]
@jpuri can you suggest how to make callback after every typing of user? Not sure about others but I felt that for any suggestions it is quite normal to have this feature.

**Comment by jpuri** [comment]
Hi @nitinagrawal08 , I totally agree on having this feature, but the above approach will result in unnecessary AJX calls, this should be done only if:
1. There is a key input 
2. Current select is mention

**Comment by nitinagrawal08** [comment]
@jpuri looks like there are gaps in my understanding of editor code flow. I am not sure how to proceed further on this.

**Comment by nitinagrawal08** [comment]
I found a work around for this functionality by pulling mention content in OnEditorStateChange in my implementation... It is kind of working although not hundred percent as suggestions appear only after user puts a space

**Pull request closed without merging**
