### PR TITLE
Alucas/feature/counter

### PR DESCRIPTION
**Pull request by andresin87**
First approach of the counter plugin.

ezgif com-crop 2

### CODE REVIEW

**Comment by andreslucas** [comment]
[WIP]

**Comment by jpuri** [comment]
Great work @andresin87, I will be happy to merge it once completed.

**Comment by andreslucas** [comment]
Ok @jpuri I tested the tool and, in my opinion, it's working fine. Test it whenever you want.

**Comment by jpuri** [comment]
@andresin87: thanks sure I will check this out soon 👍

**Pull request closed without merging**
