### PR TITLE
Add callback for getting changed mention text

### PR DESCRIPTION
**Pull request by alfaslash**
I need to get changed text for mention because I'm loading array of suggestions from API.
I added function `onChangeMention`, it's return only text for mention.

I would be grateful, if suggest other ways to get it is.

### CODE REVIEW

**Comment by jpuri** [comment]
@alfaslash : Thanks a lot for the PR, I will soon review it and I will get back to you.

**Comment by jpuri** [comment]
Hi @alfaslash ,
I looked at the PR, I do not exactly understand the requirement, can you plz help me understand - do you need to get mention text whenever a mention is applied using the call back ?

**Comment by alfaslash** [comment]
Hi, @jpuri 
That's the case:
```
class CustomEditor extends React.Component {
	constructor(props, context) {
		super(props, context);
		this.state = {
                        editorState: this.editorState,
			persons: []
		};
	}

	// get mentions filtered by `changedMention`
       async onChangeMention(changedMention) {
		const persons = await loadPersons(changedMention);
		this.setState({ persons });
	}

        render () {
		return (
			<Editor
				editorState={this.state.editorState}
				onEditorStateChange={this.onEditorStateChange}
				mention={{
					separator: ' ',
					trigger: '@',
                                         ...
					suggestions: this.state.persons
				}}
			/>
		);
	}
}

// get persons collection from API
function loadPersons(searchWord) {
    fetch(`/persons?searchWord=${searchWord}`)
        .then(response => response.json())
        .catch(e);
}
```

When the user types a text `@alf` (for example) I should be able to get users collection filtered by text `alf`. This is the case autocomplete on the server.

**Comment by jpuri** [comment]
Ok, thanks. I will again review / test the changes and release.

**Comment by alfaslash** [comment]
@jpuri What about the changes on this PR?

**Comment by jpuri** [comment]
@alfaslash : Sorry for the delay, I am merging this and will release hopefully today after some testing.

**Comment by jpuri** [comment]
@alfaslash : i see an issue. Will this not result in call back being called each time decorator parses the text, ideally we would prefer it to be executed only while user is typing.

**Pull request merged**
