### PR TITLE
Update to support React v18

### PR DESCRIPTION
**Pull request by AlexHolderDeveloper**
Similar to the PR that added support for React v17, just changing the package.json.

### CODE REVIEW

**Comment by inform880** [comment]
Hey, this is blocking me, any way it can get merged soon?

**Comment by AlexHolderDeveloper** [comment]
@jpuri please have a look at this, thankyou.

**Comment by allicanseenow** [comment]
Would be nice to have this resolved soon.

**Comment by CaioRolla** [comment]
up

**Comment by garyodendaal** [comment]
@jpuri is there any way you could look into merging this soon.

**Comment by extraReal** [comment]
Would love to use with react 18 so +1

**Comment by faizalajiw** [comment]
Please merge

**Review by faizalajiw — APPROVED** [review]
good

**Comment by jpuri** [comment]
Thanks @AlexHolderDeveloper : I will soon release a new version of the lib and share it here.

**Comment by allicanseenow** [comment]
Thanks @jpuri. Appreciate the work.

**Comment by AlimovSV** [comment]
@jpuri please publish npm package

**Comment by copoer** [comment]
Howdy @jpuri,
Please publish the npm package. This would be very useful for me.
Also, Thank you for your work on the package :+1:

**Comment by essa-mor** [comment]
Please publish, I really need this change
Thanks

**Comment by kamikhanz** [comment]
@jpuri  please publish

**Comment by MiriFr** [comment]
> @jpuri please publish

**Comment by pinkfloydsito** [comment]
@jpuri please publish

**Comment by Hostek** [comment]
can't install with react 18

**Comment by jpuri** [comment]
I published https://www.npmjs.com/package/react-draft-wysiwyg/v/1.15.0 with the change.

**Comment by mourice-oduor** [comment]
Hello @jpuri , dropdowns are not working using react-draft-wysiwyg in React.js version 18.

**Comment by anujaksThinkpalm** [comment]
Hi @jpuri Dropdowns are not working

**Comment by mourice-oduor** [comment]
> I published https://www.npmjs.com/package/react-draft-wysiwyg/v/1.15.0 with the change.

Hello, @jpuri kindly make changes for it to support version 18 of react. Many options are down.

**Comment by thomasters17** [comment]
Hello @jpuri , dropdowns are not working using react-draft-wysiwyg in React.js version 18. Please can we get a fix urgently?

**Comment by NikitaLukashuk1** [comment]
@AlexStormwood did you fork it?

**Comment by NikitaLukashuk1** [comment]
@jpuri sorry for disturbing, but, I forked your repo, added some changes, and now can't build it with react 18, because of some libs which uses react-17
but I still can't figure out, how it was working before I forked it with

**Pull request merged**
