### PR TITLE
Prevent crash when drag and dropping image from another browser.

### PR DESCRIPTION
**Pull request by gablabelle**
Prevent crash when drag and dropping image from another browser into the image uploader.

For #247

### CODE REVIEW

**Comment by jpuri** [comment]
Hey @gablabelle : can you plz create PR for just the fix.

**Comment by gablabelle** [comment]
Hmm this seems really odd... This PR is only suppose to contain the fixes for drag and drop. I will check with @Amitom about these merges ... but he's on holiday until next week. We'll get back to you.

cc: @lavoiedn

**Comment by jpuri** [comment]
@gablabelle : did you had a chance to check the PR ?

**Comment by lavoiedn** [comment]
@jpuri I tried to do some clean up on this branch with @gablabelle I think everything is in order now but we'll run some tests on our end and update as needed.

**Comment by jpuri** [comment]
Hi @gablabelle . Sorry for this delay. I see this branch has only 1 file changes but 9 commits. Can you plz rebase and submit again.

**Comment by lavoiedn** [comment]
@jpuri I took care of the rebase, though I must admit this was the first time I had to deal with such a complicated rebase... If something went wrong, just poke me and I'll see what I can do to fix it.

**Comment by jpuri** [comment]
@lavoiedn: In that case I think it might be better to pull latest code and paste your changes over it since its only 1 file.

**Comment by lavoiedn** [comment]
@jpuri That was pretty much the result of the rebase; I checked out the `fixes/drag-and-drop-improvements` branch, used `git rebase -i jpuri/react-draft-wysiwig/master` and gave the command to keep the last two commits out of the 9 that were in the branch before the rebase but to squash them.

The [diff](https://github.com/jpuri/react-draft-wysiwyg/pull/248/files) shows only the changes that are required for the fix.

As with any rebase, the only possible issue is if someone based a branch on the commits that no longer exist, but I doubt this was the case here.

**Comment by jpuri** [comment]
Thanks a lot for your efforts - yep I think its highly un-probable someone based their branches on these commit.
Nice work 👍

**Pull request merged**
