### PR TITLE
Detect youtube/vimeo/dailymotion url and convert them to embed url

### PR DESCRIPTION
**Pull request by inspiredjw**
I added a detection, used [embed-video](https://github.com/alanshaw/embed-video), for `youtube/vimeo/dailymotion` url and convert them to proper embed url.

When it fails to detect those url, it fallbacks to the raw url input.

This change might help this issue https://github.com/jpuri/react-draft-wysiwyg/issues/155

### CODE REVIEW

**Comment by macsplan** [comment]
any luck on getting this merged in?

**Comment by hoantran-it** [comment]
I'm waiting for this PR to be merged. Please!

**Comment by helmerdavila** [comment]
This could be merged?

**Comment by jpuri** [comment]
Hi All, I see embedded functionality has a gap. I am working on change to add callback prop for embedding, so this piece of code can be included in the callback.

**Comment by jpuri** [comment]
Plz find the PR merged: https://github.com/jpuri/react-draft-wysiwyg/pull/763

Here is am example: https://github.com/jpuri/react-draft-wysiwyg/blob/master/stories/Embeddable/index.js

Change is available in this version: `react-draft-wysiwyg@1.12.14`

**Comment by jpuri** [comment]
Thanks  a lot @inspiredjw , its nice work. Reason I did not merged it as is, is that I do not want behaviour to change for all users. Only those who need this change will be able to use callback.

**Comment by muralimallow** [comment]
Hi
https://vimeo.com/ondemand/avgn/104184630 is not working, Only it allowed http://

**Pull request closed without merging**
