### PR TITLE
Imge : Add default size override

### PR DESCRIPTION
**Pull request by Amitom**
In response to https://github.com/jpuri/react-draft-wysiwyg/issues/220

### CODE REVIEW

**Comment by amitava82** [comment]
This is very much essential as default width 100% brakes alignment when rendered as html.

**Comment by jpuri** [comment]
Thanks @Amitom, looks good. I will merge and release it soon.

**Comment by jpuri** [comment]
Thanks again @Amitom , cool stuff 👍 

Its my bad to delay releasing it, appreciate ur efforts.

**Comment by Abhiramborige** [comment]
Hey, is the customizable image resizing option implemented, waiting for it @jpuri

**Pull request merged**
