### PR TITLE
draft-js dependencies update

### PR DESCRIPTION
**Pull request by ktjd123**
didn't add draft-js in package.json

### CODE REVIEW

**Comment by jpuri** [comment]
Its a peer dependency already, why is this needed to add it to the lib ?

**Comment by peter1262** [comment]
because it doesn't add draft-js module automatically from yarn or npm it gives an error "draft-js"is not found

**Comment by jpuri** [comment]
Yep its little hassle to add peer-dependencies of the lib, but draft-js will be huge increase to bundle size. I want to check out some bundle size optimization options before I add it.

**Comment by peter1262** [comment]
okay

**Comment by jpuri** [comment]
Closing as discussed above.

**Comment by Nitheeshskumar** [comment]
> Yep its little hassle to add peer-dependencies of the lib, but draft-js will be huge increase to bundle size. I want to check out some bundle size optimization options before I add it.

Have you found any bundle size reducin gtechniques for draftjs? Please share. It would be really helpful

**Pull request closed without merging**
