### PR TITLE
Feature/aria attrs

### PR DESCRIPTION
**Pull request by jpuri**

### CODE REVIEW

**Comment by jpuri** [comment]
Thanks @andreslucas

**Comment by andreslucas** [comment]
Nice job. This project is awesome!

**Comment by jpuri** [comment]
Thanks @andreslucas 😄  nice feedbacks are always go motivating.

**Comment by sureshHARDIYA** [comment]
Great. @andreslucas, could you share the code for demos you had for https://andresin87.github.io/wysiwyg/.

**Pull request merged**
