### PR TITLE
Feature/translations

### PR DESCRIPTION
**Pull request by Amitom**

### CODE REVIEW

**Comment by jpuri** [comment]
Cool stuff @Amitom. Thanks a ton - I will soon review it in details and merge 👍

**Comment by jpuri** [comment]
Hey @Amitom: are these changes also complete and ready to be merged ?

Looking forward to including them.

**Comment by Amitom** [comment]
Hi, I need to resolve conflicts before, maybe this evening (Canada - East time :) ), but I think all is translated !

**Comment by mguijarr** [comment]
Thanks a ton @Amitom

**Comment by jpuri** [comment]
Awesome stuff @Amitom 👍

**Comment by Amitom** [comment]
@jpuri when a try to run the master branch to test in the playground there is an error, he can't find the draftjs-to-html/markdown modules :(

Otherwise I think my PR is ready to merge.

**Comment by jpuri** [comment]
Let me check @Amitom.

**Comment by jpuri** [comment]
Hey @Amitom:

Cool stuff. I am getting this error in latest master code now. Any guess:

```
Uncaught Error: [React Intl] Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry.
    at invariant (bundle.js:40591)
    at invariantIntlContext (bundle.js:10779)
    at new InjectIntl (bundle.js:10851)
    at bundle.js:42649
    at measureLifeCyclePerf (bundle.js:42429)
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (bundle.js:42648)
    at ReactCompositeComponentWrapper._constructComponent (bundle.js:42634)
    at ReactCompositeComponentWrapper.mountComponent (bundle.js:42542)
    at Object.mountComponent (bundle.js:10318)
    at ReactDOMComponent.mountChildren (bundle.js:47099)
```

**Comment by Amitom** [comment]
I'll take a look about this error.

**Comment by Amitom** [comment]
Ah ah, there was a merge f***, I will fix it today, sorry !

**Comment by bang88** [comment]
Hi all, can we use Intl now ?

**Comment by jpuri** [comment]
Hey @Amitom: thx, do this fix earliest.

@bang88: I will soon release this feature, you can use it then.

**Comment by bang88** [comment]
Okay when you get done please let me know.thank you so much

**Comment by the1sky** [comment]
@Amitom , expect fixed version, thanks
@jpuri ,master branch should always right,thanks

**Comment by jpuri** [comment]
`react-draft-wysiwyg@1.7.9` Released with support for internationalization 🎉

**Comment by roychoo** [comment]
👏

**Comment by mguijarr** [comment]
Wonderful !  Thanks a lot. I really love this library.

**Pull request merged**
