### PR TITLE
Upstream add block indent

### PR DESCRIPTION
**Pull request by dpetranek**
Allow indenting text #474:

This adds a basic block-level indent. It's a pretty dumb implementation that relies on shift+enter to keep subsequent lines indented to the same level, but I don't think it will be difficult to extend it so that it maintains the indentation level of the previous block. (Though, I do think it would be nice to swap the default behavior of `enter` and `shift+enter`).

Another problem is compatibility with the list-indent functionality. I think ideally they should be merged. If you have any thoughts on the best way to do that, I'd be happy to hear them - should the merged indents live in their own top-level option?

Any feedback is welcome.

### CODE REVIEW

**Comment by dpetranek** [comment]
I've just realized that this formatting doesn't survive a round trip translation from EditorState -> html -> EditorState. It looks like I'll need a way to add an inline style to the block.

**Comment by jpuri** [comment]
@dpetranek : you can try to use block level meta-data and custom renderer for this. I used it for text-alignment also.

**Comment by jpuri** [comment]
Hey @dpetranek : if you can plz rebase it on develop branch. I will check and merge this after fixing the issue with saving it.

**Comment by dpetranek** [comment]
Hello @jpuri, I've rebased successfully. The only changes I had to make were updating two tests for the number of child elements (6 by default, 7 in dropdown).

**Comment by jpuri** [comment]
Hey @dpetranek , can you plz base it on `develop` branch instead of `master`. I would prefer to test out changes before releasing.

**Comment by dpetranek** [comment]
It looks like it's based on develop on my end. The head of develop is 4db5f28 and 4db5f28 is the commit immediately before mine on this branch, so I think we should be good. 

Maybe I'm misunderstanding, though, so just let me know what you need and I'll see what I can do.

**Comment by dpetranek** [comment]
Wait, I figured out what you were talking about, and I think I resolved it. Take another look and let me know, thanks!

**Comment by alan345** [comment]
hi!
Option 
`textAlign: { options: ['left', 'center', 'right', 'justify', 'indent', 'outdent'] },`
is not working.. This PR have been merged, right?

**Pull request merged**
