### PR TITLE
Include TEXTAREA as a tagName that should be focused

### LINKED ISSUE #567: Cannot get focused on textarea inside modal of custom control
Hello, this is weird

i tried adding <textarea> on custom controll component and cannot focus on it while  if i replace it with input it is working.

you can test it with this 

```
class CustomOption extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      value: ""
    };
  }
  render() {
    return (
      <textarea
        value={this.state.value}
        onChange={e => this.setState({ value: e.target.value })}
      />
    );
  }
}

const EditorCustomToolbarOption = () => (
  <Editor
    wrapperClassName="demo-wrapper"
    editorClassName="demo-editor"
    toolbarCustomButtons={[<CustomOption />]}
  />
);
```
if you replace textarea with input you will see it is work normally
Why this happen?

### PR DESCRIPTION
**Pull request by agerbens**
Fixes #567

### CODE REVIEW

**Comment by bobeagan** [comment]
@jpuri any chance we can get this merged and a new release created? Hate to have to maintain a fork for this small change.  Thanks!

**Comment by bobeagan** [comment]
@jpuri is this repository abandoned?

**Comment by jpuri** [comment]
@agerbens , @bobeagan : Looking into this.

**Comment by jpuri** [comment]
`react-draft-wysiwyg@1.13.2` has this change.

**Pull request merged**
