### PR TITLE
Feature link return input value

### PR DESCRIPTION
**Pull request by brod-dotdev**

### CODE REVIEW

**Comment by george-dotdev** [comment]
This would be a great pr.

**Comment by b0123498765** [comment]
Really amazing PR! Are you the guy who created netlify-local by any chance?

**Comment by seromenho** [comment]
What do you guys think of #768 ?

**Comment by jpuri** [comment]
Just released `react-draft-wysiwyg@1.13.0` with the fix.

**Comment by brod-dotdev** [comment]
> What do you guys think of #768 ?

For our case (relative links and search params) just getting the original input was enough but I think a hook of sorts would be very useful.

**Pull request merged**
