### PR TITLE
fix bug: the toolbar will hide abnormally  when uploading images if set toolbarOnFocus=true

### PR DESCRIPTION
**Pull request by nodejh**
If set `toolbarOnFocus=true`,  the toolbar will hide  abnormally when I open files in my computer during uploading. Because the editor will lose focus when I open files , so that toolbar will be hidden. 

I think the toolbar should keep visible if image component or others are expanded. So I fixed it.

Before:

react-before

After:
react-after

### CODE REVIEW

**Comment by jpuri** [comment]
Hey @nodejh , thanks a lot for the PR, it looks good. Can you plz rebase it on develop branch rather so I can play around with it and merge.

**Comment by nodejh** [comment]
Hi @jpuri, I changed the base branch to develop.

**Comment by jpuri** [comment]
Thanks 👍 , I will check this soon.

**Comment by jpuri** [comment]
Hey @nodejh : I made a simpler fix for the scenario: https://github.com/jpuri/react-draft-wysiwyg/pull/563

**Pull request merged**
