### PR TITLE
Add image preview option to image upload modal

### PR DESCRIPTION
**Pull request by paradoxxxzero**
This PR adds a `previewImage` option to preview uploaded image instead of the url which is particularly useful when "uploading" image as a data-uri. I also added a story about that.  (I updated some dependencies, I can revert if you want.)

screenshot from 2017-10-10 11-59-10

### CODE REVIEW

**Comment by gablabelle** [comment]
@paradoxxxzero @jpuri ... Yes the URL preview is kind of useless. Should be able to preview image instead or to simply embed image right away and close the Image dropdown right after without any previews.

screen shot 2017-10-10 at 2 44 38 pm

**Comment by paradoxxxzero** [comment]
There's still some options that can be set after (alt and size)

**Comment by gablabelle** [comment]
@paradoxxxzero In our project, we hide these options from the UI.

**Comment by shakdoesgithub** [comment]
this is awesome and really helpful. 
@jpuri what would it take to get this merged?

**Comment by jpuri** [comment]
Sorry for the delay @paradoxxxzero , and thanks a lot for nice work.

**Pull request merged**
